class CreateServants < ActiveRecord::Migration
  def self.up
    create_table :servants do |t|
      # Name of the servant. Used by code to reference this servant
      # specifically.
      t.string :name 
      # URL to connect to servant.
      t.string :url
      # Protocol the servant uses. Not written explicitly by user;
      # used to cache protocol.
      t.text :protocol
      t.timestamps
    end
    # prevent duplicate names. Note: The error generated by this must
    # be caught and parsed out by controller logic to make sense to user
    add_index :servants, :name, :unique => true
  end

  def self.down
    remove_index :servants, :column => :name
    drop_table :servants
  end
end
